/* eslint-disable import/no-anonymous-default-export */
export default [
    {
      Subject: "Mathematical Foundations forComputing (21CS41)",
      abbriviation: "21CS41",
      StaffName: "Dr.Sivasankar",
      GoogleClassroom: "",
      GoogleSite: "https://sites.google.com/rvei.edu.in/os-4thsem-2021batch--ise-cse?pli=1",
    },
    {
      Subject: "Design and Analysis of Algorithms(21CS42)",
      abbriviation: "DAA",
      StaffName: "Prof. DEEPAK D.J(DDJ)",
      GoogleClassroom: "",
      GoogleSite: "https://sites.google.com/rvei.edu.in/daa21cs42",
    },
    {
      Subject: "Microcontroller and EmbeddedSystems (21CS43)",
      abbriviation: "MES",
      StaffName: "Dr. NIHARIKA P KUMAR(NPK)", 
      GoogleClassroom: "",
      GoogleSite: "https://sites.google.com/rvei.edu.in/ivsemmces-18cs44/home",
    },
    {
      Subject: "Operating System (21CS44 ) ",
      abbriviation: "OS",
      StaffName: "Dr. LATHA C A (LCA) ",
      GoogleClassroom: "",
      GoogleSite: "https://sites.google.com/rvei.edu.in/os-4thsem-2021batch--ise-cse?pli=1",
    },
    {
      Subject: "Biology For Engineers (21BE45)",
      abbriviation: "21BE45",
      StaffName: "Dr. Harish H (HH)",
      GoogleClassroom: "",
      GoogleSite: "https://sites.google.com/rvei.edu.in/os-4thsem-2021batch--ise-cse?pli=1",
    },
    {
      Subject: "Python Programming Laboratory(21CSL46)",
      abbriviation: "21CSL46",
      StaffName: "AA,SD,KK",
      GoogleClassroom: "",
      GoogleSite: "https://sites.google.com/rvei.edu.in/os-4thsem-2021batch--ise-cse?pli=1",
    },
    // {
    //   Subject: "Design and Analysis of AlgorithmLaboratory (18CSL47)",
    //   abbriviation: "DAA Lab",
    //   StaffName: "DDJ,LCA,KK",
    //   GoogleClassroom: "",
    //   GoogleSite: "",
    // },
    // {
    //   Subject: "Microcontroller and Embedded SystemsLaboratory (18CSL48)",
    //   abbriviation: "MES Lab",
    //   StaffName: "NPK,SD",
    //   GoogleClassroom: "",
    //   GoogleSite: "",
    // },
    {
      Subject: "Constitution of India & ProfessionalEthics (21CIP47)",
      abbriviation: "",
      StaffName: "Mr. Vijaya Kumar",
      GoogleClassroom: "CIP",
      GoogleSite: "",
    },
    {
      Subject: "UnixShell Programming (21CS482)",
      abbriviation: "AE",
      StaffName: "SP",
      GoogleClassroom: "21CS482",
      GoogleSite: "https://sites.google.com/d/1z1naNCqnmg2WicmfBPwey3c-KXNMZuQG/edit",
    },
    {
      Subject: "Universal Human Values (21UH49)",
      abbriviation: "21UH49",
      StaffName: "Mr.Thejas",
      GoogleClassroom: "",
      GoogleSite: "",
    },
    // {
    //   Subject: "Additional Mathematics - II (21MATDIP41)",
    //   abbriviation: "DIPMAT",
    //   StaffName: "Dr.Nagabhushan",
    //   GoogleClassroom: "",
    //   GoogleSite: "",
    // },
  ];